// Capstone — design template skeleton.
// Run: node demo.js
//
// This isn't a runnable agent. It's a printable design template you fill in.

const template = `
# AGENT DESIGN — <name>

## 1. Goal
What does this agent do? Whose problem does it solve?
- User: ...
- Trigger: ...
- Outcome: ...

## 2. Architecture
\`\`\`
[diagram of components: orchestrator, workers, memory, tools, observability]
\`\`\`

## 3. Tools
| Name | Description | Inputs | Returns | Errors |
|------|-------------|--------|---------|--------|
| ...  | ...         | ...    | ...     | ...    |

## 4. System prompt
\`\`\`
1. Role: ...
2. Capabilities: ...
3. Operating rules:
   You MUST: ...
   You MUST NOT: ...
4. Output format: ...
5. Examples: ...
6. Edge cases: ...
\`\`\`

## 5. Memory model
- Persistent: ...
- Session-only: ...
- Schema: ...
- TTL / GC: ...

## 6. Multi-agent shape
- [ ] Single agent
- [ ] Orchestrator + N workers
- [ ] Pipeline of N stages
- [ ] Other: ...
Justification: ...

## 7. Failure modes
| Mode | Detection | Response |
|------|-----------|----------|
| Looping | repetition detector | terminate |
| Hallucinated tool | schema validation | surface to LLM |
| Off-task drift | LLM-as-judge | warning observation |
| ... | ... | ... |

## 8. Observability
- Per-run trace: thought, action, observation, tokens, ms.
- Metrics: pass rate, p50/p95 latency, cost.
- Storage: ...

## 9. Cost model
- Estimated tokens per run: ...
- Cost per run: ...
- Budget cap: ...
- Optimizations applied: model routing, caching, parallelism.

## 10. Autonomy level
- Starting level: ...
- Per-action policy: ...
- Promotion criteria: ...
- Rollback plan: ...

## 11. Eval suite
- Number of fixtures: ...
- Check types: schema, containment, llm_judge, ...
- Baseline pass rate: ...
- Regression alert threshold: ...

## 12. Open questions
- ...
- ...
`;

console.log(template);

console.log(`
Take note:
  - This template covers the territory the dojo trained you on.
  - Filling it in IS the design. Building from it should be mechanical.
  - If a section is hard to fill, you've found a gap. Address it.
  - The retrospective at the end of your build will probably point at one of these
    sections that you handwaved. That's the section to revisit.
`);
